### ISSUE TITLE
Re-evaluate where we define our Dockerfile build-args

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2928]
Intuitively, defining our build-args like this:

```Dockerfile
ARG DISTRO_VERSION=7
ARG NCPU=4
FROM centos:${DISTRO_VERSION} AS devtools
```

in a multi-stage build should work as expected. But it doesn't. `NCPU` will be empty in the second stage:

```Dockerfile
Step 14/14 : RUN cmake --build cmake-out -- -j ${NCPU}
 ---> Running in 1d5b2ee2b116
/usr/bin/ninja-build: option requires an argument -- 'j'
usage: ninja-build [options] [targets...]

if targets are unspecified, builds the 'default' target (see manual)
```

The following does **not** work:

```Dockerfile
ARG NCPU=4
FROM devtools AS readme
```

It needs to be after:

```Dockerfile
FROM devtools AS readme
ARG NCPU=4
```

See https://github.com/moby/moby/issues/34129 for discussion.

**Comment by remyabel** [comment]
FTR, using Ninja caught this bug. Using `make -j` without an argument puts no limits on the amount of parallel jobs, whereas it appears that Ninja will complain. I'll do a more thorough sweep to see where else NCPU might be misused.

**Comment by coryan** [comment]
Fixed by #2929.

**Comment by remyabel** [comment]
It's not fixed yet. I haven't made the PR with the NCPU changes yet.
