### ISSUE TITLE
GCP C++ SDK - Setting HTTP proxy and disabling SSL certificate verification

### ISSUE THREAD

**Issue by adhitya97** [googleapis/google-cloud-cpp#5584]
How can we set HTTP proxy for GCP C++ SDK?

Setting env variables using the "http_proxy" does not seem to have an effect.

Setting the SSL_CERT_FILE env variable also does not affect the SSL certificate path. CURL always seems to be using the default certificate directory.

Also, is there a way to disable SSL certificate verification in the GCP C++ SDK?

**Comment by coryan** [comment]
> How can we set HTTP proxy for GCP C++ SDK?

Can you let us know which library are you trying to use?  Most likely this is the storage library, as the other libraries use gRPC as their transport, and you reference CURL specifically.  It would also be useful to know if you build against the native CURL, or you are building your own.

> 
> Setting env variables using the "http_proxy" does not seem to have an effect.

Because the library uses `https` by default. If you want to use a proxy for `https://` requests you need to set `https_proxy`:

https://ec.haxx.se/usingcurl/usingcurl-proxies

> Setting the SSL_CERT_FILE env variable also does not affect the SSL certificate path. CURL always seems to be using the default certificate directory.

Ack.

> 
> Also, is there a way to disable SSL certificate verification in the GCP C++ SDK?

I am not aware of any. If you are trying to use the library to access public data you can use `http://` as the endpoint.  Maybe you can share more about what is it that you are trying to do and why disabling certificate verification would be useful?

**Comment by adhitya97** [comment]
I am trying to use the Google Storage library. 


Also, following up on the SSL_CERT_FILE env variable, even setting the ChannelOptions through set_ssl_root_path() doesn't seem to be working properly in the absence of the ca-certificates package. 


This is the code snippet that I am following - 

```
google::cloud::storage::ChannelOptions channelOptions;
 channelOptions.set_ssl_root_path("path/to/abc.crt");
_clientOptions = new google::cloud::storage::ClientOptions(*_credentials, channelOptions);
```

I have the ca-certificates package uninstalled. If the package is installed, the set_ssl_root_path is working as expected.

Is that the right way to do it?

**Comment by coryan** [comment]
> I am trying to use the Google Storage library.

Ack.  Can you share how are you building it, what platform, etc?

> Also, following up on the SSL_CERT_FILE env variable, even setting the ChannelOptions through set_ssl_root_path() doesn't seem to be working properly in the absence of the ca-certificates package.
> 
> This is the code snippet that I am following -
> 
> ```
> google::cloud::storage::ChannelOptions channelOptions;
>  channelOptions.set_ssl_root_path("path/to/abc.crt");
> _clientOptions = new google::cloud::storage::ClientOptions(*_credentials, channelOptions);
> ```
> 
> I have the ca-certificates package uninstalled. If the package is installed, the set_ssl_root_path is working as expected.

This might be related to #5524 knowing what version of the library you are using could help us diagnose that.

> 
> Is that the right way to do it?

Yes, that should work, modulo using a recent enough version that includes the fixes in #5524

**Comment by adhitya97** [comment]
> This might be related to #5524 knowing what version of the library you are using could help us diagnose that.

Yes, it seems to have been fixed with #5524.


> Ack. Can you share how are you building it, what platform, etc?

I am using it inside a Debian 10 docker container - trying to make GCP storage CPP SDK use a HTTP proxy.

**Comment by coryan** [comment]
Seems like this problem is resolved then?  If you have further questions please do not hesitate to open a new issue.

**Comment by adhitya97** [comment]
> This might be related to #5524 knowing what version of the library you are using could help us diagnose that.
> Yes, it seems to have been fixed with #5524.


Sorry, this fix (#5524) still does not seem remove the dependency on the ca-certificates package. Usage of custom certificates specified while creating credentials

`google::cloud::storage::ChannelOptions channelOptions;
 channelOptions.set_ssl_root_path("path/to/abc.crt");
_clientOptions = new google::cloud::storage::ClientOptions(*_credentials, channelOptions);`

are still failing in the latest master

**Comment by coryan** [comment]
We are going to need more information to reproduce this locally:

- How are you running the application?
  - Seems like this is a Debian 10-based container, without the `ca-certificates` installed.
  - It also seems that your networking setup requires an https_proxy.
  - What kind of credentials are you using?  Service Account?  User? I am going to guess "service account", is that correct?
  - Is your proxy configured to work with the `https://oauth2.googleapis.com/token` service too? The library uses that to create an access token from service account credentials.

- How are you compiling the library?
   - What Linux distribution are you using?  Earlier you said "Debian 10", but it is unclear if you compile with the same distro you use to the application linked against the library.
   - What compiler?
   - What version of the library?
   - What options did you provide in your `cmake` configuration step.

**Comment by adhitya97** [comment]
> How are you running the application?

- I am running a Debian 10-based container, without the ca-certificates package installed.
- Currently, I am not making use of a HTTP proxy, though the end goal is to do so. 
- I am using a service account  

> Is your proxy configured to work with the https://oauth2.googleapis.com/token service too? The library uses that to create an access token from service account credentials.
We can ignore the proxy for now

> What Linux distribution are you using? Earlier you said "Debian 10", but it is unclear if you compile with the same distro you use to the application linked against the library.
I am using the same distribution to compile

> What compiler?
GCC

> What version of the library?
v1.21.0


> What options did you provide in your cmake configuration step.

```
cd $HOME/google-cloud-cpp
cmake -DBUILD_TESTING=OFF -H. -Bcmake-out
cmake --build cmake-out -- -j "${NCPU:-4}"
sudo cmake --build cmake-out --target install
```

**Comment by coryan** [comment]
Thanks for the detailed information.  Clearly this is not a feature I use a lot because I had completely forgotten about the need to set the channel options when you create the service account credentials.  You want to create your credentials with this function:

https://github.com/googleapis/google-cloud-cpp/blob/00671b0972e27d66301a56801e3f7859e56d3439/google/cloud/storage/oauth2/google_credentials.h#L148-L151

I was able to first reproduce the problem and then got the code to work using this program:

https://github.com/googleapis/google-cloud-cpp/compare/master...coryan:repro-5584

Let me know if that does not work for you.

**Comment by adhitya97** [comment]
One of the packages you install is the ca-certificates package. What is the necessity of that package? 

If the ssl_root_path is given in the ChannelOptions to make use of a static certificate, there should ideally be no necessity for the ca-certificates package. 


Could you run the same program you used to reproduce the bug, but without the ca-certificates package installed inside the container?


I have a very similar program, which works with the ChannelOptions (ssl_root_path) when ca-certificates is installed. But, it does not work without that package

**Comment by coryan** [comment]
> One of the packages you install is the ca-certificates package.

For the initial stages: yes.

> What is the necessity of that package?

I think you are assuming that package was used in the final test, it is not. The Dockerfile is a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/).  The final stage does not install the package:

https://github.com/coryan/google-cloud-cpp/blob/3bf2a21e9dea5b642c2955ef3cf90b2f19eb4f04/google/cloud/storage/tests/repro-5584/repro-5584.Dockerfile#L90-L98

> Could you run the same program you used to reproduce the bug, but without the ca-certificates package installed inside the container?

See above. In the final stage the `ca-certificates` package is **not** installed.  I just verified that with:

```sh
root@273876da301f:/r# apt search ca-certificates 
Sorting... Done
Full Text Search... Done
ca-certificates/stable-updates 20200601~deb10u1 all
  Common CA certificates

ca-certificates-java/stable 20190405 all
  Common CA certificates (JKS keystore)

ca-certificates-mono/stable 5.18.0.240+dfsg-3 all
  Common CA certificates (Mono keystore)

```

and the program runs:

```sh
root@273876da301f:/r# /r/repro-5584 $BUCKET_NAME $JSON_FILE /r/roots.pem 
Successfully created object: ObjectMetadata={name=repro-5584.txt, .... ... ... 
```

**Comment by adhitya97** [comment]
Okay. This program does work for me. Thank you for the clarifications!
